Add lua support
Wilfred/difftastic pull request #188
Opened 2022-03-28 16:31 UTC by JafarAbdi

- Add lua.scm from nvim-treesitter
- Finish lua support
- Revert "Add lua.scm from nvim-treesitter" for some reason it's causing the program to panic

I'll take a look on why adding the highlights is causing the program to panic

2022-03-29 05:06 UTC, Wilfred commented on src/tree_sitter_parser.rs
> +                delimiter_tokens: (vec![("(", ")"), ("{", "}")])
This look sensible, but for Lua you'll want `[` `]` too.

2022-03-29 05:14 UTC, Wilfred requested changes
Thanks! Lua is definitely a language I'd like to see in difftastic.

> I'll take a look on why adding the highlights is causing the program to panic

Sometimes the panic message is useful, so I'd look at that first. You don't have to have highlights, an empty string is fine, but of course it's nicer to have highlighting.

I think neovim may have extended the query syntax with lua scripting:

https://github.com/nvim-treesitter/nvim-treesitter/blob/3b974b7257516e4ea89d10dd9842b1035a540d7e/queries/lua/highlights.scm#L137

It might work if you remove the `#lua-match?` queries.

Otherwise, this is almost ready to merge! You can fix the formatting by running `cargo fmt`. You'll also need to update the sample files output test:

```
$ sample_files/compare_all.sh
$ cp sample_files/compare.result sample_files/compare.expected
```

This isn't super well documented at the moment, I'll look to fix that.

2022-03-29 21:17 UTC, JafarAbdi commented
@Wilfred Are you going to squash merge this? or should I squash the last few commits?

2022-03-30 02:30 UTC, Wilfred commented
@JafarAbdi please squash the last few commits, and then I will merge this :)

2022-03-30 05:08 UTC, merged

2022-03-30 05:08 UTC, Wilfred commented
Thanks :)