Add Janet support
Wilfred/difftastic pull request #190
Opened 2022-03-29 01:24 UTC by sogaiu

This PR is an attempt to add support for the [Janet programming language](https://janet-lang.org/), a language with a lisp-ish / clojure-ish syntax.

In Janet, mutable collections are distinguished from immutable ones via a leading `@`.  In the tree-sitter grammar used in this PR, `@{`, `@(`, and `@[` are tokens indicating opening delimiters.  I hope the following code in `src/tree_sitter_parser.rs` was appropriate:
```
delimiter_tokens: (vec![("@{", "}"), ("@(", ")"), ("@[", "]"),
                        ("{", "}"), ("(", ")"), ("[", "]")])
```

2022-03-29 05:04 UTC, Wilfred requested changes
Other than the display name, this looks pretty good :)

I just need two changes before merging:

(1) Run the formatter (you can run `cargo fmt`).

(2) Add a sample file to `sample_files/` and run `./sample_files/compare_all.sh; cp sample_files/compare.result sample_files/compare.expected`. That way we can see everything is set up correctly and will stay working in future.

2022-03-29 05:10 UTC, sogaiu commented on src/tree_sitter_parser.rs
> +                name: "Janet Simple",
Just to give some background, there is [another tree-sitter grammar for Janet](https://github.com/GrayJack/tree-sitter-janet) so my intent was to leave room for it.

Should I still change the name to "Janet"?

2022-03-29 05:17 UTC, Wilfred commented on src/tree_sitter_parser.rs
> +                name: "Janet Simple",
Yes please -- I think it's unlikely difftastic will end up with multiple parsers for the same language, and this feels like an implementation detail.

2022-03-29 05:18 UTC, sogaiu commented on src/tree_sitter_parser.rs
> +                name: "Janet Simple",
Thanks for the clarification.

2022-03-29 05:59 UTC, sogaiu commented
@Wilfred I've made attempts to address:

* changing the display name to "Janet"
* formatting the code with `cargo fmt`
* adding sample files and updating `compare.expected`

Please let me know if those went ok and/or there is anything else.

2022-03-30 02:32 UTC, merged

2022-03-30 02:32 UTC, Wilfred commented
Thanks!